server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  # sleuth & zipkin相关配置starts
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1  # 采样率介于0-1之间，若设置为1，则全部采集，但性能损耗
  # sleuth & zipkin相关配置ends

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/springcloud2020?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 1234

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.gengyu.springcloud.entities   # 所有Entity别名类所在包

eureka:
#  instance:
#    prefer-ip-address: true
  client:
    service-url:
#      defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
    register-with-eureka: true  # 默认即为true
    fetch-registry: true        # 默认即为true
  instance:
    instance-id: payment8001  # 在Eureka页面上，服务名由这个名字来代替默认的主机名称:端口号
    prefer-ip-address: true   # 在Eureka页面上，鼠标放在项目名称上，左下角会显示ip地址
#    lease-renewal-interval-in-seconds: 1
#    lease-expiration-duration-in-seconds: 2
