server:
  port: 2001

spring:
  application:
    name: seata-order-service
  cloud:
    alibaba:
      seata:
        tx-service-group: siegfried_tx_group  # 在file.conf中service块中指定的组名
    nacos:
      discovery:
        server-addr: localhost:8848

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seata_order
    username: root
    password: 1234

feign:
  hystrix:
    enabled: false

#logging:
#  level:
#    io: seata

mybatis:
  mapper-locations: classpath:mapper/*.xml
